import { useQuery } from "@tanstack/react-query";
import { fetchWeatherApi } from "openmeteo";
import type { LocationResponse } from "./useLocationQuery";
import {
  getWeekDay,
  type WeekDay,
  type WeekDayNumber,
} from "../helpers/helpers";
import type { WeatherCode } from "../components/WeatherIcon";

/**
 * Query the Open Meteo weather API based on a chosen location.
 */
export default function useWeatherQuery(
  chosenLocation: LocationResponse | null,
) {
  const latitude = chosenLocation?.latitude;
  const longitude = chosenLocation?.longitude;

  return useQuery({
    queryKey: ["weather", { latitude, longitude }],
    queryFn: () =>
      // Query function will not be executed until a lat/long exists, due to
      // the 'enabled' option. Hence the type assertion.
      fetchAndParseAPIResult(latitude as number, longitude as number),
    enabled: !!chosenLocation,
  });
}

const API_URL = "https://api.open-meteo.com/v1/forecast";

const API_SETTINGS = {
  daily: ["weather_code", "temperature_2m_max", "temperature_2m_min"],
  hourly: ["temperature_2m", "weather_code"],
  current: [
    "temperature_2m",
    "apparent_temperature",
    "relative_humidity_2m",
    "wind_speed_10m",
    "precipitation",
    "weather_code",
  ],
};

export type ParsedWeatherResponse = Awaited<
  ReturnType<typeof fetchAndParseAPIResult>
>;

/**
 * The Open-Meteo API client API returns its response data in a binary format, rather than
 * a JSON encoding. This function uses parses the binary data and extracts the chosen weather variables.
 *
 * The parsing code in this function is generated by the docs.
 */
async function fetchAndParseAPIResult(latitude: number, longitude: number) {
  const params = {
    latitude,
    longitude,
    ...API_SETTINGS,
  };

  const responses = await fetchWeatherApi(API_URL, params);

  // An array of responses is returned to account for multiple selected locations etc. This app
  // only uses one location.
  const response = responses[0];

  // Different timezones are represented with a UTC offset.
  const utcOffsetSeconds = response.utcOffsetSeconds();

  const currentUnparsed = response.current()!;
  const hourlyUnparsed = response.hourly()!;
  const dailyUnparsed = response.daily()!;

  // The order of the 'variables' index must match the order given in the API settings object.
  // Both were generated by the API docs and so should match.
  const current = {
    time: new Date((Number(currentUnparsed.time()) + utcOffsetSeconds) * 1000),
    temperature_2m: currentUnparsed.variables(0)!.value(),
    apparent_temperature: currentUnparsed.variables(1)!.value(),
    relative_humidity_2m: currentUnparsed.variables(2)!.value(),
    wind_speed_10m: currentUnparsed.variables(3)!.value(),
    precipitation: currentUnparsed.variables(4)!.value(),
    weather_code: currentUnparsed.variables(5)!.value(),
  };

  const hourly = {
    time: Array.from(
      {
        length:
          (Number(hourlyUnparsed.timeEnd()) - Number(hourlyUnparsed.time())) /
          hourlyUnparsed.interval(),
      },
      (_, i) =>
        new Date(
          (Number(hourlyUnparsed.time()) +
            i * hourlyUnparsed.interval() +
            utcOffsetSeconds) *
            1000,
        ),
    ),
    temperature_2m: hourlyUnparsed.variables(0)!.valuesArray(),
    weather_code: hourlyUnparsed.variables(1)!.valuesArray(),
  };

  const daily = {
    time: Array.from(
      {
        length:
          (Number(dailyUnparsed.timeEnd()) - Number(dailyUnparsed.time())) /
          dailyUnparsed.interval(),
      },
      (_, i) =>
        new Date(
          (Number(dailyUnparsed.time()) +
            i * dailyUnparsed.interval() +
            utcOffsetSeconds) *
            1000,
        ),
    ),
    weather_code: dailyUnparsed.variables(0)!.valuesArray(),
    temperature_2m_max: dailyUnparsed.variables(1)!.valuesArray(),
    temperature_2m_min: dailyUnparsed.variables(2)!.valuesArray(),
  };

  interface TimeSlotData {
    time: Date;
    temperature: number | null;
    weatherCode: WeatherCode | null;
  }

  const hourlyGroupedByDay = hourly.time.reduce<
    Partial<Record<WeekDay, TimeSlotData[]>>
  >((acc, time, index) => {
    const day = getWeekDay(time.getDay() as WeekDayNumber);

    const timeSlotData = {
      time: time,
      temperature: hourly.temperature_2m?.[index] ?? null,
      weatherCode: hourly.weather_code?.[index] ?? null,
    };

    if (acc[day] === undefined) {
      acc[day] = [];
    }

    acc[day].push(timeSlotData);

    return acc;
  }, {});

  return {
    current,
    hourlyGroupedByDay,
    daily,
  };
}
