import { useQuery } from "@tanstack/react-query";
import { fetchWeatherApi } from "openmeteo";
import type { LocationResponse } from "./useLocationQuery";

/**
 * Query the Open Meteo weather API based on a chosen location.
 */
export default function useWeatherQuery(
  chosenLocation: LocationResponse | null,
) {
  const latitude = chosenLocation?.latitude;
  const longitude = chosenLocation?.longitude;

  return useQuery({
    queryKey: ["weather", { latitude, longitude }],
    queryFn: () =>
      // Query function will not be executed until a lat/long exists, due to
      // the 'enabled' option. Hence the type assertion.
      fetchAndParseAPIResult(latitude as number, longitude as number),
    enabled: !!chosenLocation,
  });
}

const API_URL = "https://api.open-meteo.com/v1/forecast";

const API_SETTINGS = {
  daily: ["weather_code", "temperature_2m_max", "temperature_2m_min"],
  hourly: ["temperature_2m", "weather_code"],
  current: [
    "temperature_2m",
    "apparent_temperature",
    "relative_humidity_2m",
    "wind_speed_10m",
    "precipitation",
  ],
};

/**
 * The Open-Meteo API client API returns its response data in a binary format, rather than
 * a JSON encoding. This function uses parses the binary data and extracts the chosen weather variables.
 *
 * The parsing code in this function is generated by the docs.
 */
async function fetchAndParseAPIResult(latitude: number, longitude: number) {
  const params = {
    latitude,
    longitude,
    ...API_SETTINGS,
  };

  const responses = await fetchWeatherApi(API_URL, params);

  // An array of responses is returned to account for multiple selected locations etc. This app
  // only uses one location.
  const response = responses[0];

  // Different timezones are represented with a UTC offset.
  const utcOffsetSeconds = response.utcOffsetSeconds();

  const current = response.current()!;
  const hourly = response.hourly()!;
  const daily = response.daily()!;

  // The order of the 'variables' index must match the order given in the API settings object.
  // Both were generated by the API docs and so should match.
  const weatherData = {
    current: {
      time: new Date((Number(current.time()) + utcOffsetSeconds) * 1000),
      temperature_2m: current.variables(0)!.value(),
      apparent_temperature: current.variables(1)!.value(),
      relative_humidity_2m: current.variables(2)!.value(),
      wind_speed_10m: current.variables(3)!.value(),
      precipitation: current.variables(4)!.value(),
    },
    hourly: {
      time: Array.from(
        {
          length:
            (Number(hourly.timeEnd()) - Number(hourly.time())) /
            hourly.interval(),
        },
        (_, i) =>
          new Date(
            (Number(hourly.time()) + i * hourly.interval() + utcOffsetSeconds) *
              1000,
          ),
      ),
      temperature_2m: hourly.variables(0)!.valuesArray(),
      weather_code: hourly.variables(1)!.valuesArray(),
    },
    daily: {
      time: Array.from(
        {
          length:
            (Number(daily.timeEnd()) - Number(daily.time())) / daily.interval(),
        },
        (_, i) =>
          new Date(
            (Number(daily.time()) + i * daily.interval() + utcOffsetSeconds) *
              1000,
          ),
      ),
      weather_code: daily.variables(0)!.valuesArray(),
      temperature_2m_max: daily.variables(1)!.valuesArray(),
      temperature_2m_min: daily.variables(2)!.valuesArray(),
    },
  };

  return weatherData;
}
